### ISSUE TITLE
Convert Actions require turning off my branch protection rules

### ISSUE THREAD

**Issue by noinarisak** [instruqt/skeleton#1]
Hi there,

These GH Actions, scripts, and workflow are great. Thanks for offering this Template repo!

However, running through the [tutorial](https://docs.instruqt.com/how-to-guides/build-tracks/maintain-a-developer-workflow), the `convert` Actions fails on the "Commit Changes" steps in [generate-track-slugs.yml](https://github.com/instruqt/skeleton/blob/d583fa20c955d600ea69580b3ad78c4a2c3f97e0/.github/workflows/generate-track-slugs.yml#L31)

Steps:

1. Setup the repo per the tutorial.
2. Active Branch protection rule. ie. On repo, Setting tab > Branches > Add rule for `main` branch > Check `Require a pull request before merging` > Create.
3. Run `convert` actions as detailed in the tutorial.
4. See that the "Commit Changes" failed due to the Branch protection rule.

Ask:

* Offer a work around, with out de-activating the branch protection rule

**Comment by morey-tech** [comment]
The workaround I used (without going through the effort of setting up authentication for the `git-auto-commit-action` step) is to create a new branch from `main` (where the branch protection is) and run the `generate` workflow against it. Then create a pull request from the branch and go through the process to adhere to the branch protections.

**Comment by scarolan** [comment]
We are refactoring this to remove the track-slugs file altogether so this will no longer be necessary.
