### ISSUE TITLE
Improved docs and tutorials

### ISSUE THREAD

**Issue by scarolan** [instruqt/skeleton#24]
Instruqt docs and video example should be updated with the new, simpler workflow instructions.

**Comment by scarolan** [comment]
@jpelchat please update our docs and howto to reflect the latest workflow changes.

**Comment by jeff-french** [comment]
Any ETA on the updated docs? Trying to piece it all together based on the action updates but full docs would be great.

**Comment by scarolan** [comment]
They're updated now @jeff-french
